version: "3.8"

services:
  backend:
    build: ./weather
    container_name: weather_backend
    ports:
      - "8000:8000"
    volumes:
      - ./weather:/app
    restart: always
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost  # Modify as needed

  frontend:
    build: ./client
    container_name: weather_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules  # Prevents overriding installed node_modules
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:8000  # Ensure frontend talks to backend
    depends_on:
      - backend
    restart: always


volumes:
  pg_data:
