version: "3.8"

services:
  backend:
    build: ./  # Build from the root since weather/ and api/ are part of the backend
    container_name: weather_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount the entire backend
    restart: always
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1

  frontend:
    build: ./client
    container_name: weather_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: always


volumes:
  pg_data:
