version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_backend
    ports:
      - "9000:9000"
    volumes:
      - ./weather:/app/weather
      - ./manage.py:/app/manage.py
      - ./api:/app/api
    env_file:
      - .env
    restart: always

  frontend:
    build: ./client
    container_name: weather_frontend
    ports:
      - "4000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    depends_on:
      - backend
    restart: always

volumes:
  pg_data:
