version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_backend
    ports:
      - "9000:9000"
    volumes:
      - ./weather:/app/weather
      - ./manage.py:/app/manage.py
      - ./api:/app/api
      - ./entrypoint.dev.sh:/app/entrypoint.dev.sh
    env_file:
      - .env
    entrypoint: /app/entrypoint.dev.sh
    restart: always

  frontend:
    build: ./client
    container_name: weather_frontend
    ports:
      - "4000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    restart: always

  postgis:
    image: postgis/postgis:13-3.1
    container_name: postgis_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=local_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    profiles:
      - dev

volumes:
  pg_data:
