# Generated by Django 5.1.5 on 2025-02-24 17:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', 'create_weather_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_index', models.IntegerField()),
                ('start_time_offset', models.DurationField()),
                ('start_distance_km', models.FloatField()),
                ('end_distance_km', models.FloatField()),
                ('segment_point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('segment_line', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='api.trail')),
            ],
        ),
        migrations.DeleteModel(
            name='TestGeometry',
        ),
    ]
