# Generated by Django 5.1.5 on 2025-03-22 17:00

from django.db import migrations, models
import django.contrib.gis.db.models.fields

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_trailsegment_delete_testgeometry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrailSegment',
        ),
        migrations.DeleteModel(
            name='Trail',
        ),

        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=8000, null=True, blank=True)),
                ('county', models.CharField(max_length=130, null=True, blank=True)),
                ('activity', models.CharField(max_length=50, null=True, blank=True)),
                ('description', models.TextField(null=True, blank=True)),
                ('website', models.URLField(max_length=8000, null=True, blank=True)),
                ('length_km', models.FloatField(null=True, blank=True)),
                ('difficulty', models.CharField(max_length=1000, null=True, blank=True)),
                ('trail_type', models.CharField(max_length=1000, null=True, blank=True)),
                ('ascent_metres', models.CharField(max_length=1000, null=True, blank=True)),
                ('start_point', models.CharField(max_length=1000, null=True, blank=True)),
                ('finish_point', models.CharField(max_length=1000, null=True, blank=True)),
                ('nearest_town_start', models.CharField(max_length=1000, null=True, blank=True)),
                ('nearest_town_finish', models.CharField(max_length=1000, null=True, blank=True)),
                ('public_transport', models.CharField(max_length=1000, null=True, blank=True)),
                ('dogs_allowed', models.CharField(max_length=256, null=True, blank=True)),
                ('management_organisation', models.CharField(max_length=1000, null=True, blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, blank=True)),
                ('route', django.contrib.gis.db.models.fields.MultiLineStringField(geography=True, null=True, blank=True, srid=4326)),
            ],
        ),

        migrations.CreateModel(
            name='TrailSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_index', models.IntegerField()),
                ('start_time_offset', models.DurationField()),
                ('start_distance_km', models.FloatField()),
                ('end_distance_km', models.FloatField()),
                ('segment_point', django.contrib.gis.db.models.fields.PointField(geography=True)),
                ('segment_line', django.contrib.gis.db.models.fields.LineStringField(geography=True)),
                ('trail', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='segments', to='api.Trail')),
            ],
        ),
    ]
