# Generated by Django 5.1.5 on 2025-03-22 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_trailsegment_delete_testgeometry'),
        ('api', 'create_user_weather_alert'),
    ]

    operations = [
    ]
